#Set up is quick and easy. Simply replace the example text below with your nonprofit's information.
#If you'd like to leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line
#If you see '> # Enter on the next line', be sure to leave the two spaces in front of your text on that next line

#Required organization information
org_name: Project Example
org_summary: > # Enter your summary on the next line
  A mobile-friendly Github Pages template designed to help grassroots nonprofits get a website online quickly
org_full_description: > # Enter your description on the next line
  Ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.

#Optional organization information
org_general_email_inbox: your-email@somedomain.com
org_street_address: 1355 Market Street #Please include suite number on the line below
org_address_suite: Suite 900
org_city: San Francisco
org_state: CA
org_zip: > # Enter zip on next line
  94103
org_phone: > # Enter phone on next line
  (123) 456-7890
#Non US-address support coming soon :)

#Are you currently a registered 501(c)3 organization?
#If you are, remove the hashtag symbol (#) below
#501c3: true

#Email signups and donations
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: free-template-demo
tinyletter_username: interestingnonprofits

#social media
twitter_username: smartergiving
facebook_username: smartergiving
instagram_username:

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Choose color scheme
#Options are: one, two, three, four, or default. Options one through four follow the color schemes at http://themes.3rdwavemedia.com/website-templates/devaid-free-bootstrap-theme-developers/
theme: default

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
